######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 19 22:30:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += JuliaFrame.h JuliaMath.h JuliaWidget.h
SOURCES += JuliaFrame.cpp JuliaMath.cpp JuliaWidget.cpp main.cpp
